plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.6.4.cjs

packageExtensions:
  "@parcel/transformer-image@2.0.1":
    dependencies:
      "@parcel/core": "*"
  "@parcel/types@2.0.1":
    dependencies:
      "@parcel/core": "*"
